batch_size: 16
val_batch_size: 4
sample_size: None # Set by the training loop, from dataset config.
sample_size_anchor: None # Set by the training loop, from dataset config.
num_wta_trials: 20
num_trials: 1