name: df_cross

# Model settings
type: point # (flow, point) Type of model
size: xS # (xs, s, ...) Architecture of DiT
in_channels: 3 # Number of input channels
learn_sigma: True # Learn sigma for diffusion
center_noise: False # Center noise for diffusion
rotary: False # Use rotary embedding for diffusion

x_encoder: mlp # Encoder current timestep x
y_encoder: mlp # (mlp, dgcnn) Encoder for y object (e.g. anchor pcd)
x0_encoder: mlp # (mlp, dgcnn) Encoder for x0 object (e.g. action pcd)

# diffusion settings
diff_train_steps: 100 # Number of diffusion steps during training
diff_inference_steps: 100 # Number of diffusion steps during inference
diff_noise_schedule: linear # (linear, cosine) Noise schedule for diffusion
diff_noise_scale: 1.0 # Scale of noise for diffusion
diff_type: gaussian