lr: 1e-4
lr_warmup_steps: 100
weight_decay: 1e-5
epochs: 20000
batch_size: 16
val_batch_size: 1
grad_clip_norm: 1.0
num_training_steps: None # Set by the training loop.

check_val_every_n_epochs: 200
num_wta_trials: 100