lr: 1e-4
lr_warmup_steps: 100
weight_decay: 1e-5
epochs: 20000
batch_size: 16
val_batch_size: 16
grad_clip_norm: 1.0
num_training_steps: None # Set by the training loop.
training_sample_size: None # Set by the training loop, from dataset config.

check_val_every_n_epochs: 100
num_wta_trials: 20

prediction_error_type: distractor_min # [demo, distractor_min], type of prediction error to use